### PR TITLE
Fix/cross component update warning

### LINKED ISSUE #234: Upgrade to React 16.13.1 creates a new console warning
Hi guys,

Hope you're doing well.

React 16.13.x introduces a new warning 

https://github.com/facebook/react/blob/master/CHANGELOG.md#react-dom-1
- Warn when a function component is updated during another component's render phase (@acdlite in #17099)

As soon as we update, we have this warning thrown, something like described here

- https://github.com/facebook/react/issues/18178#issuecomment-596266655

Warning can be seen easily through one of your example (maybe other examples too)

- https://codesandbox.io/s/github/ioof-holdings/redux-dynostore/tree/master/examples/real-world

> Warning: Cannot update a component (`ConnectFunction`) while rendering a different component (`Dynamic(Connect(App))`). To locate the bad setState() call inside `Dynamic(Connect(App))`, follow the stack trace as described in https://fb.me/setstate-in-render
>     in Dynamic(Connect(App)) (at Routes.js:11)
>     in LoadableComponent (at Routes.js:30)
>     in Route (at Routes.js:27)
>     in Routes (at Root.dev.js:12)
>     in Router (created by ConnectedRouter)
>     in ConnectedRouter (created by Context.Consumer)
>     in ConnectedRouterWithContext (created by ConnectFunction)
>     in ConnectFunction (at Root.dev.js:11)
>     in div (at Root.dev.js:10)
>     in Provider (at Root.dev.js:9)
>     in Root (at src/index.js:9)

### PR DESCRIPTION
**Pull request by mpeyper**
| Q                       | A
| ----------------------- | ---
| Fixed Issues?           | Fixes #234
| Documentation only PR   | 
| Patch: Bug Fix?         | 
| Minor: New Feature?     | 
| Major: Breaking Change? | 
| Tests Added + Pass?     | Yes

Moved the store and component enhancement of the "dynamic target" chain into `useEffect` of `dynamic`, preventing the `attachReducer` call (and any other enhancers that trigger a store update`) from updating the store in the main render path.

This change has an assumption that is is ok to render `null` for a single render until the store has been updated.  Once the effect has triggered, the enhanced component will be created and set into state where it can be safely rendered in the subsequent renders.  I think this is ok, but it is a change from the existing functionality, although it may improve a previously raised issues around concurrent mode and render tearing (where some of the rendering uses a particular instance of state and the another part uses a different instance of state, potentially creating inconsistent output).

I'm not sure if this should be a breaking change, in case anyone is relying on this behaviour, a minor change, because we may have introduced a new feature to prevent tearing, or a minor change, because we're fixing a warning about a potential bugs.

I'm leaning towards a major version, but I'm also open to being convinced it only a minor or patch version.

### CODE REVIEW

**Comment by mpeyper** [comment]
This has been published as version `3.1.1-alpha.0` (for all packages) for anyone that want's to try it out.  Please let me know if you have any issues.

**Comment by Ethorsen** [comment]
Hey @mpeyper,

Just tested 3.1.1-alpha.0 with React 16.13.1. 

So far so good, I'm seeing no difference at all in our application which heavily rely on dynostore/subspaces. Warning from react is gone.

I will keep pushing the tests but at this point I'm pretty confident I won't find any new/modified behavior. We will probably commit to use you alpha release until it makes its way into an official release. 

Thank you very much for your efforts

**Comment by mpeyper** [comment]
Thanks for the feedback @Ethorsen.  Assuming this is still working fine for you (please let me know otherwise), I'll get this into a release soon.

**Comment by mpeyper** [comment]
This has (finally) been released in `v3.1.1`

**Comment by jlowcs** [comment]
it seems like this fix is causing regressions when using SSR: https://github.com/ioof-holdings/redux-dynostore/issues/473

**Pull request merged**
